"""
Tests for vibe.architect_agent.
Generated by rapid_test_generator.py
"""

import json
import os
from unittest.mock import AsyncMock, MagicMock, patch

import pytest

os.environ["APP_ENV"] = "testing"

try:
    from src.vibe.architect_agent import (
        ArchitectAgent,
        ArchitecturePattern,
        ArchitecturePlan,
        Component,
        DataFlow,
    )

    IMPORTS_AVAILABLE = True
except ImportError as e:
    print(f"Import error for vibe.architect_agent: {e}")
    IMPORTS_AVAILABLE = False


class TestArchitecturePattern:
    """Test ArchitecturePattern."""

    @pytest.mark.skipif(not IMPORTS_AVAILABLE, reason="Module not available")
    def test_architecture_pattern_values(self):
        """Should have correct ArchitecturePattern values."""
        assert ArchitecturePattern.MICROSERVICES.value == "microservices"
        assert ArchitecturePattern.MONOLITH.value == "monolith"
        assert ArchitecturePattern.EVENT_DRIVEN.value == "event_driven"
        assert ArchitecturePattern.MVC.value == "mvc"
        assert ArchitecturePattern.SERVERLESS.value == "serverless"
        assert ArchitecturePattern.LAYERED.value == "layered"
        assert ArchitecturePattern.HEXAGONAL.value == "hexagonal"
        assert ArchitecturePattern.SPA.value == "spa"
        assert ArchitecturePattern.REST_API.value == "rest_api"
        assert ArchitecturePattern.WEBSOCKET_API.value == "websocket_api"


class TestComponent:
    """Test Component."""

    @pytest.mark.skipif(not IMPORTS_AVAILABLE, reason="Module not available")
    def test_create_component(self):
        """Should create Component."""
        instance = Component(
            id="comp_001",
            name="Test Component",
            type="service",
            description="A test component",
            responsibilities=["handle requests"],
            interfaces=["REST API"],
            dependencies=[],
        )
        assert instance is not None
        assert instance.id == "comp_001"
        assert instance.name == "Test Component"


class TestDataFlow:
    """Test DataFlow."""

    @pytest.mark.skipif(not IMPORTS_AVAILABLE, reason="Module not available")
    def test_create_dataflow(self):
        """Should create DataFlow."""
        instance = DataFlow(
            from_component="comp_001",
            to_component="comp_002",
            data_type="JSON",
            protocol="HTTP",
            description="Data flow between components",
        )
        assert instance is not None
        assert instance.from_component == "comp_001"
        assert instance.to_component == "comp_002"


class TestArchitecturePlan:
    """Test ArchitecturePlan."""

    @pytest.mark.skipif(not IMPORTS_AVAILABLE, reason="Module not available")
    def test_create_architecture_plan(self):
        """Should create ArchitecturePlan."""
        plan = ArchitecturePlan(
            pattern=ArchitecturePattern.MICROSERVICES,
            overview="A microservices-based system",
            components=[
                Component(
                    id="service1",
                    name="UserService",
                    type="service",
                    description="Handles user operations",
                    responsibilities=["Create user", "Update user"],
                    interfaces=["REST API"],
                    dependencies=["Database"],
                )
            ],
            data_flows=[
                DataFlow(
                    from_component="UserService",
                    to_component="Database",
                    data_type="JSON",
                    protocol="HTTP",
                    description="User data persistence",
                )
            ],
            technology_stack={
                "backend": ["Python", "FastAPI"],
                "database": ["PostgreSQL"],
            },
            non_functional_requirements={
                "scalability": "High",
                "availability": "99.9%",
            },
            diagram="graph TD",
            considerations=["Security", "Performance"],
        )
        assert plan.pattern == ArchitecturePattern.MICROSERVICES
        assert len(plan.components) == 1
        assert len(plan.data_flows) == 1


class TestArchitectAgent:
    """Test ArchitectAgent."""

    @pytest.fixture(autouse=True)
    def setup_mocks(self):
        """Setup common mocks for all tests."""
        with (
            patch("src.vibe.architect_agent.AutoGenIntegration") as mock_autogen,
            patch("src.vibe.architect_agent.LiteLLMRouter") as mock_llm,
            patch("src.vibe.architect_agent.get_settings") as mock_settings,
        ):
            mock_settings.return_value = MagicMock()
            mock_autogen.return_value = MagicMock()
            mock_llm.return_value = MagicMock()
            self.mock_autogen = mock_autogen
            self.mock_llm = mock_llm
            self.mock_settings = mock_settings
            yield

    @pytest.mark.skipif(not IMPORTS_AVAILABLE, reason="Module not available")
    def test_create_agent(self):
        """Should create ArchitectAgent."""
        agent = ArchitectAgent()
        assert agent.config is not None
        assert agent.autogen is not None
        assert agent.llm_router is not None
        assert len(agent.pattern_keywords) > 0
        assert len(agent.component_types) > 0

    @pytest.mark.skipif(not IMPORTS_AVAILABLE, reason="Module not available")
    def test_detect_pattern_microservices(self):
        """Should detect microservices pattern."""
        agent = ArchitectAgent()

        requirements = "Build a distributed system with microservices and APIs"
        pattern = agent._detect_pattern(requirements, None)

        assert pattern == ArchitecturePattern.MICROSERVICES

    @pytest.mark.skipif(not IMPORTS_AVAILABLE, reason="Module not available")
    def test_detect_pattern_mvc(self):
        """Should detect MVC pattern."""
        agent = ArchitectAgent()

        requirements = "Create an MVC web application with model view controller"
        pattern = agent._detect_pattern(requirements, None)

        assert pattern == ArchitecturePattern.MVC

    @pytest.mark.skipif(not IMPORTS_AVAILABLE, reason="Module not available")
    def test_detect_pattern_serverless(self):
        """Should detect serverless pattern."""
        agent = ArchitectAgent()

        requirements = "Implement serverless functions with lambda"
        pattern = agent._detect_pattern(requirements, None)

        assert pattern == ArchitecturePattern.SERVERLESS

    @pytest.mark.skipif(not IMPORTS_AVAILABLE, reason="Module not available")
    def test_detect_pattern_event_driven(self):
        """Should detect event-driven pattern."""
        agent = ArchitectAgent()

        requirements = "Design an event-driven architecture with message queues"
        pattern = agent._detect_pattern(requirements, None)

        assert pattern == ArchitecturePattern.EVENT_DRIVEN

    @pytest.mark.skipif(not IMPORTS_AVAILABLE, reason="Module not available")
    def test_detect_pattern_monolith(self):
        """Should detect monolith pattern."""
        agent = ArchitectAgent()

        requirements = "Build a single monolithic application"
        pattern = agent._detect_pattern(requirements, None)

        assert pattern == ArchitecturePattern.MONOLITH

    @pytest.mark.skipif(not IMPORTS_AVAILABLE, reason="Module not available")
    def test_detect_pattern_spa(self):
        """Should detect SPA pattern."""
        agent = ArchitectAgent()

        requirements = "Create a single page application with React"
        pattern = agent._detect_pattern(requirements, None)

        assert pattern == ArchitecturePattern.SPA

    @pytest.mark.skipif(not IMPORTS_AVAILABLE, reason="Module not available")
    def test_detect_pattern_rest_api(self):
        """Should detect REST API pattern."""
        agent = ArchitectAgent()

        requirements = "Build a REST API with HTTP endpoints"
        pattern = agent._detect_pattern(requirements, None)

        assert pattern == ArchitecturePattern.REST_API

    @pytest.mark.skipif(not IMPORTS_AVAILABLE, reason="Module not available")
    def test_detect_pattern_websocket(self):
        """Should detect WebSocket API pattern."""
        agent = ArchitectAgent()

        requirements = "Implement real-time communication with websockets"
        pattern = agent._detect_pattern(requirements, None)

        assert pattern == ArchitecturePattern.WEBSOCKET_API

    @pytest.mark.skipif(not IMPORTS_AVAILABLE, reason="Module not available")
    def test_detect_pattern_with_context(self):
        """Should detect pattern considering context."""
        agent = ArchitectAgent()

        requirements = "Build a web application"
        context = {"existing_components": ["UserService", "ProductService"]}

        pattern = agent._detect_pattern(requirements, context)

        # Should detect some pattern based on requirements
        assert isinstance(pattern, ArchitecturePattern)

    @pytest.mark.skipif(not IMPORTS_AVAILABLE, reason="Module not available")
    def test_generate_diagram(self):
        """Should generate Mermaid diagram."""
        agent = ArchitectAgent()

        plan = ArchitecturePlan(
            pattern=ArchitecturePattern.MICROSERVICES,
            overview="Test system",
            components=[
                Component(
                    id="api",
                    name="API Gateway",
                    type="api",
                    description="Gateway",
                    responsibilities=[],
                    interfaces=[],
                    dependencies=[],
                ),
                Component(
                    id="service",
                    name="UserService",
                    type="service",
                    description="User service",
                    responsibilities=[],
                    interfaces=[],
                    dependencies=["api"],
                ),
            ],
            data_flows=[
                DataFlow(
                    from_component="api",
                    to_component="service",
                    data_type="JSON",
                    protocol="HTTP",
                    description="API calls",
                )
            ],
            technology_stack={},
            non_functional_requirements={},
            diagram="",
            considerations=[],
        )

        diagram = agent._generate_diagram(plan)

        assert "graph" in diagram
        assert "api" in diagram
        assert "service" in diagram

    @pytest.mark.skipif(not IMPORTS_AVAILABLE, reason="Module not available")
    def test_create_basic_plan(self):
        """Should create basic architecture plan."""
        agent = ArchitectAgent()

        requirements = "Build a web application"
        pattern = ArchitecturePattern.MICROSERVICES

        plan = agent._create_basic_plan(requirements, pattern)

        assert isinstance(plan, ArchitecturePlan)
        assert plan.pattern == ArchitecturePattern.MICROSERVICES
        assert len(plan.components) > 0

    @pytest.mark.skipif(not IMPORTS_AVAILABLE, reason="Module not available")
    def test_has_circular_dependency(self):
        """Should detect circular dependencies."""
        agent = ArchitectAgent()

        # Create a plan with circular dependency
        plan = ArchitecturePlan(
            pattern=ArchitecturePattern.MICROSERVICES,
            overview="Test system",
            components=[
                Component(
                    id="service1",
                    name="Service1",
                    type="service",
                    description="Test service",
                    responsibilities=[],
                    interfaces=[],
                    dependencies=["service2"],
                ),
                Component(
                    id="service2",
                    name="Service2",
                    type="service",
                    description="Test service",
                    responsibilities=[],
                    interfaces=[],
                    dependencies=["service1"],
                ),
            ],
            data_flows=[],
            technology_stack={},
            non_functional_requirements={},
            diagram="",
            considerations=[],
        )

        # Should detect circular dependency
        has_circular = agent._has_circular_dependency(plan, "service1", set())
        assert has_circular is True

    @pytest.mark.skipif(not IMPORTS_AVAILABLE, reason="Module not available")
    def test_generate_microservices_diagram(self):
        """Should generate microservices diagram."""
        agent = ArchitectAgent()

        plan = ArchitecturePlan(
            pattern=ArchitecturePattern.MICROSERVICES,
            overview="Test system",
            components=[
                Component(
                    id="api",
                    name="API Gateway",
                    type="api",
                    description="Gateway",
                    responsibilities=[],
                    interfaces=[],
                    dependencies=[],
                )
            ],
            data_flows=[],
            technology_stack={},
            non_functional_requirements={},
            diagram="",
            considerations=[],
        )

        diagram = agent._generate_microservices_diagram(plan)

        assert "graph" in diagram
        assert "API_Gateway" in diagram

    @pytest.mark.skipif(not IMPORTS_AVAILABLE, reason="Module not available")
    def test_generate_rest_diagram(self):
        """Should generate REST API diagram."""
        agent = ArchitectAgent()

        plan = ArchitecturePlan(
            pattern=ArchitecturePattern.REST_API,
            overview="Test API",
            components=[
                Component(
                    id="api",
                    name="REST API",
                    type="api",
                    description="API",
                    responsibilities=[],
                    interfaces=[],
                    dependencies=[],
                )
            ],
            data_flows=[],
            technology_stack={},
            non_functional_requirements={},
            diagram="",
            considerations=[],
        )

        diagram = agent._generate_rest_diagram(plan)

        assert "graph" in diagram
        assert "REST_API" in diagram

    @pytest.mark.skipif(not IMPORTS_AVAILABLE, reason="Module not available")
    async def test_create_architecture(self):
        """Should create architecture with mocked LLM."""
        agent = ArchitectAgent()

        # Mock the LLM response as JSON string
        mock_response = json.dumps(
            {
                "overview": "E-commerce platform architecture",
                "components": [
                    {
                        "id": "frontend",
                        "name": "Frontend App",
                        "type": "ui",
                        "description": "React-based frontend",
                        "responsibilities": ["Display products", "Handle checkout"],
                        "interfaces": ["HTTP API"],
                        "dependencies": ["api_gateway"],
                        "technology": "React",
                    }
                ],
                "data_flows": [
                    {
                        "from_component": "frontend",
                        "to_component": "api_gateway",
                        "data_type": "JSON",
                        "protocol": "HTTPS",
                        "description": "API calls",
                    }
                ],
                "technology_stack": {
                    "frontend": ["React", "TypeScript"],
                    "backend": ["Node.js", "Express"],
                    "database": ["MongoDB"],
                },
                "non_functional_requirements": {
                    "scalability": "High",
                    "performance": "<200ms response time",
                },
                "considerations": ["Security", "Scalability", "Performance"],
            }
        )

        # Create a proper async mock for the generate method
        async def mock_generate(*args, **kwargs):
            return mock_response

        agent.llm_router.generate = mock_generate

        requirements = "Build an e-commerce platform with product catalog and checkout"
        context = {"team_size": 5, "timeline": "3 months"}

        plan = await agent.create_architecture(requirements, context)

        assert isinstance(plan, ArchitecturePlan)
        assert plan.overview == "E-commerce platform architecture"
        assert len(plan.components) == 1
        assert len(plan.data_flows) == 1
        assert "React" in plan.technology_stack["frontend"]
        assert plan.diagram != ""

    @pytest.mark.skipif(not IMPORTS_AVAILABLE, reason="Module not available")
    async def test_create_architecture_mvc_pattern(self):
        """Should create MVC architecture with mocked LLM."""
        agent = ArchitectAgent()

        mock_response = json.dumps(
            {
                "overview": "Blog application with MVC pattern",
                "components": [
                    {
                        "id": "controller",
                        "name": "PostController",
                        "type": "api",
                        "description": "Handles HTTP requests",
                        "responsibilities": ["Handle CRUD operations"],
                        "interfaces": ["HTTP"],
                        "dependencies": ["model", "view"],
                        "technology": "Flask",
                    }
                ],
                "data_flows": [],
                "technology_stack": {
                    "backend": ["Python", "Flask"],
                    "database": ["SQLite"],
                },
                "non_functional_requirements": {},
                "considerations": ["Simplicity", "Rapid development"],
            }
        )

        # Create a proper async mock
        async def mock_generate(*args, **kwargs):
            return mock_response

        agent.llm_router.generate = mock_generate

        requirements = "Create a blog application using MVC architecture"

        plan = await agent.create_architecture(requirements)

        assert isinstance(plan, ArchitecturePlan)
        assert plan.pattern == ArchitecturePattern.MVC
        assert "Blog application" in plan.overview

    @pytest.mark.skipif(not IMPORTS_AVAILABLE, reason="Module not available")
    def test_generate_mvc_diagram(self):
        """Should generate MVC diagram."""
        agent = ArchitectAgent()

        plan = ArchitecturePlan(
            pattern=ArchitecturePattern.MVC,
            overview="MVC App",
            components=[
                Component(
                    id="controller",
                    name="Controller",
                    type="api",
                    description="Handles requests",
                    responsibilities=[],
                    interfaces=[],
                    dependencies=[],
                )
            ],
            data_flows=[],
            technology_stack={},
            non_functional_requirements={},
            diagram="",
            considerations=[],
        )

        diagram = agent._generate_mvc_diagram(plan)

        assert "graph" in diagram
        assert "Controller" in diagram

    @pytest.mark.skipif(not IMPORTS_AVAILABLE, reason="Module not available")
    def test_generate_generic_diagram(self):
        """Should generate generic diagram."""
        agent = ArchitectAgent()

        plan = ArchitecturePlan(
            pattern=ArchitecturePattern.LAYERED,
            overview="Layered App",
            components=[
                Component(
                    id="layer1",
                    name="Layer 1",
                    type="ui",
                    description="UI Layer",
                    responsibilities=[],
                    interfaces=[],
                    dependencies=[],
                )
            ],
            data_flows=[],
            technology_stack={},
            non_functional_requirements={},
            diagram="",
            considerations=[],
        )

        diagram = agent._generate_generic_diagram(plan)

        assert "graph" in diagram
        assert "Layer_1" in diagram

    @pytest.mark.skipif(not IMPORTS_AVAILABLE, reason="Module not available")
    def test_generate_websocket_diagram(self):
        """Should generate WebSocket API diagram."""
        agent = ArchitectAgent()

        plan = ArchitecturePlan(
            pattern=ArchitecturePattern.WEBSOCKET_API,
            overview="WebSocket App",
            components=[
                Component(
                    id="ws_server",
                    name="WebSocket Server",
                    type="api",
                    description="WebSocket server",
                    responsibilities=[],
                    interfaces=[],
                    dependencies=[],
                )
            ],
            data_flows=[],
            technology_stack={},
            non_functional_requirements={},
            diagram="",
            considerations=[],
        )

        diagram = agent._generate_diagram(plan)

        assert "graph" in diagram
        assert "WebSocket" in diagram

    @pytest.mark.skipif(not IMPORTS_AVAILABLE, reason="Module not available")
    async def test_create_architecture_with_malformed_json(self):
        """Should handle malformed JSON from LLM."""
        agent = ArchitectAgent()

        # Mock malformed JSON response
        mock_response = "{invalid json"

        async def mock_generate(*args, **kwargs):
            return mock_response

        agent.llm_router.generate = mock_generate

        requirements = "Build a simple web app"

        plan = await agent.create_architecture(requirements)

        # Should fall back to basic plan
        assert isinstance(plan, ArchitecturePlan)
        assert "Basic" in plan.overview
        assert len(plan.components) > 0

    @pytest.mark.skipif(not IMPORTS_AVAILABLE, reason="Module not available")
    async def test_create_architecture_with_llm_exception(self):
        """Should handle LLM exceptions."""
        agent = ArchitectAgent()

        # Mock LLM raising exception
        async def mock_generate(*args, **kwargs):
            raise Exception("LLM API error")

        agent.llm_router.generate = mock_generate

        requirements = "Build a web app"

        plan = await agent.create_architecture(requirements)

        # Should fall back to basic plan
        assert isinstance(plan, ArchitecturePlan)
        assert "Basic" in plan.overview
        assert len(plan.components) > 0

    @pytest.mark.skipif(not IMPORTS_AVAILABLE, reason="Module not available")
    async def test_create_architecture_with_missing_fields(self):
        """Should handle missing fields in LLM response."""
        agent = ArchitectAgent()

        # Mock response with missing fields
        mock_response = json.dumps(
            {
                "overview": "Test plan",
                # Missing components and other fields
            }
        )

        async def mock_generate(*args, **kwargs):
            return mock_response

        agent.llm_router.generate = mock_generate

        requirements = "Build a web app"

        plan = await agent.create_architecture(requirements)

        # Should create plan with empty components
        assert isinstance(plan, ArchitecturePlan)
        assert plan.overview == "Test plan"
        assert len(plan.components) == 0

    @pytest.mark.skipif(not IMPORTS_AVAILABLE, reason="Module not available")
    def test_get_components_by_type(self):
        """Should get components by type."""
        agent = ArchitectAgent()

        plan = ArchitecturePlan(
            pattern=ArchitecturePattern.MICROSERVICES,
            overview="Test system",
            components=[
                Component(
                    id="service1",
                    name="Service1",
                    type="service",
                    description="Test service",
                    responsibilities=[],
                    interfaces=[],
                    dependencies=[],
                ),
                Component(
                    id="db1",
                    name="Database1",
                    type="database",
                    description="Test database",
                    responsibilities=[],
                    interfaces=[],
                    dependencies=[],
                ),
                Component(
                    id="service2",
                    name="Service2",
                    type="service",
                    description="Another service",
                    responsibilities=[],
                    interfaces=[],
                    dependencies=[],
                ),
            ],
            data_flows=[],
            technology_stack={},
            non_functional_requirements={},
            diagram="",
            considerations=[],
        )

        services = agent.get_components_by_type(plan, "service")
        assert len(services) == 2
        assert all(c.type == "service" for c in services)

        databases = agent.get_components_by_type(plan, "database")
        assert len(databases) == 1
        assert databases[0].id == "db1"

    @pytest.mark.skipif(not IMPORTS_AVAILABLE, reason="Module not available")
    def test_get_component_by_id(self):
        """Should get component by ID."""
        agent = ArchitectAgent()

        plan = ArchitecturePlan(
            pattern=ArchitecturePattern.MICROSERVICES,
            overview="Test system",
            components=[
                Component(
                    id="service1",
                    name="Service1",
                    type="service",
                    description="Test service",
                    responsibilities=[],
                    interfaces=[],
                    dependencies=[],
                )
            ],
            data_flows=[],
            technology_stack={},
            non_functional_requirements={},
            diagram="",
            considerations=[],
        )

        component = agent.get_component_by_id(plan, "service1")
        assert component is not None
        assert component.id == "service1"

        # Test non-existent component
        component = agent.get_component_by_id(plan, "nonexistent")
        assert component is None

    @pytest.mark.skipif(not IMPORTS_AVAILABLE, reason="Module not available")
    def test_validate_plan_mvc_missing_components(self):
        """Should validate MVC pattern with missing components."""
        agent = ArchitectAgent()

        # Plan with only UI component
        plan = ArchitecturePlan(
            pattern=ArchitecturePattern.MVC,
            overview="MVC App",
            components=[
                Component(
                    id="view",
                    name="View",
                    type="ui",
                    description="UI component",
                    responsibilities=[],
                    interfaces=[],
                    dependencies=[],
                )
            ],
            data_flows=[],
            technology_stack={},
            non_functional_requirements={},
            diagram="",
            considerations=[],
        )

        issues = agent.validate_plan(plan)
        assert len(issues) > 0
        assert any("Controller" in issue for issue in issues)
        assert any("Model" in issue for issue in issues)

    @pytest.mark.skipif(not IMPORTS_AVAILABLE, reason="Module not available")
    def test_validate_plan_orphaned_dependencies(self):
        """Should validate plan with orphaned dependencies."""
        agent = ArchitectAgent()

        plan = ArchitecturePlan(
            pattern=ArchitecturePattern.MICROSERVICES,
            overview="Test system",
            components=[
                Component(
                    id="service1",
                    name="Service1",
                    type="service",
                    description="Test service",
                    responsibilities=[],
                    interfaces=[],
                    dependencies=["nonexistent_service"],
                )
            ],
            data_flows=[],
            technology_stack={},
            non_functional_requirements={},
            diagram="",
            considerations=[],
        )

        issues = agent.validate_plan(plan)
        assert len(issues) > 0
        assert any("non-existent components" in issue for issue in issues)
        assert "nonexistent_service" in issues[0]

    @pytest.mark.skipif(not IMPORTS_AVAILABLE, reason="Module not available")
    def test_validate_plan_circular_dependency(self):
        """Should validate plan with circular dependencies."""
        agent = ArchitectAgent()

        plan = ArchitecturePlan(
            pattern=ArchitecturePattern.MICROSERVICES,
            overview="Test system",
            components=[
                Component(
                    id="service1",
                    name="Service1",
                    type="service",
                    description="Test service",
                    responsibilities=[],
                    interfaces=[],
                    dependencies=["service2"],
                ),
                Component(
                    id="service2",
                    name="Service2",
                    type="service",
                    description="Test service",
                    responsibilities=[],
                    interfaces=[],
                    dependencies=["service1"],
                ),
            ],
            data_flows=[],
            technology_stack={},
            non_functional_requirements={},
            diagram="",
            considerations=[],
        )

        issues = agent.validate_plan(plan)
        assert len(issues) > 0
        assert any("Circular dependency" in issue for issue in issues)

    @pytest.mark.skipif(not IMPORTS_AVAILABLE, reason="Module not available")
    def test_export_plan(self):
        """Should export plan to JSON file."""
        agent = ArchitectAgent()

        plan = ArchitecturePlan(
            pattern=ArchitecturePattern.MICROSERVICES,
            overview="Test system",
            components=[
                Component(
                    id="service1",
                    name="Service1",
                    type="service",
                    description="Test service",
                    responsibilities=["Handle requests"],
                    interfaces=["REST API"],
                    dependencies=[],
                    technology="Python",
                )
            ],
            data_flows=[
                DataFlow(
                    from_component="service1",
                    to_component="service2",
                    data_type="JSON",
                    protocol="HTTP",
                    description="API call",
                )
            ],
            technology_stack={"backend": ["Python"]},
            non_functional_requirements={"scalability": "High"},
            diagram="graph TD",
            considerations=["Security"],
        )

        # Export to file
        import tempfile

        with tempfile.NamedTemporaryFile(mode="w", suffix=".json", delete=False) as f:
            output_path = f.name

        try:
            agent.export_plan(plan, output_path)

            # Verify file was created and contains valid JSON
            with open(output_path) as f:
                data = json.load(f)

            assert data["pattern"] == "microservices"
            assert data["overview"] == "Test system"
            assert len(data["components"]) == 1
            assert data["components"][0]["id"] == "service1"
            assert len(data["data_flows"]) == 1
            assert data["technology_stack"]["backend"] == ["Python"]
            assert data["non_functional_requirements"]["scalability"] == "High"
            assert data["diagram"] == "graph TD"
            assert data["considerations"] == ["Security"]
        finally:
            import os

            os.unlink(output_path)

    @pytest.mark.skipif(not IMPORTS_AVAILABLE, reason="Module not available")
    def test_create_markdown_report(self):
        """Should create markdown report from plan."""
        agent = ArchitectAgent()

        plan = ArchitecturePlan(
            pattern=ArchitecturePattern.MICROSERVICES,
            overview="Test microservices system",
            components=[
                Component(
                    id="service1",
                    name="User Service",
                    type="service",
                    description="Handles user operations",
                    responsibilities=["Create user", "Update user"],
                    interfaces=["REST API"],
                    dependencies=["database"],
                    technology="Python",
                ),
                Component(
                    id="db1",
                    name="User Database",
                    type="database",
                    description="User data storage",
                    responsibilities=["Store users", "Query users"],
                    interfaces=["SQL"],
                    dependencies=[],
                    technology="PostgreSQL",
                ),
            ],
            data_flows=[
                DataFlow(
                    from_component="service1",
                    to_component="db1",
                    data_type="SQL",
                    protocol="JDBC",
                    description="Database queries",
                )
            ],
            technology_stack={
                "backend": ["Python", "FastAPI"],
                "database": ["PostgreSQL"],
            },
            non_functional_requirements={
                "scalability": "High",
                "availability": "99.9%",
            },
            diagram="graph TD\n    service1 --> db1",
            considerations=["Security", "Performance"],
        )

        report = agent.create_markdown_report(plan)

        # Verify markdown structure
        assert "# Architecture Plan: Microservices" in report
        assert "## Overview" in report
        assert "Test microservices system" in report
        assert "## Components" in report
        assert "User Service" in report
        assert "Handles user operations" in report
        assert "Create user" in report
        assert "REST API" in report
        assert "Python" in report
        assert "User Database" in report
        assert "PostgreSQL" in report
        assert "## Data Flows" in report
        assert "service1" in report
        assert "db1" in report
        assert "SQL" in report
        assert "## Technology Stack" in report
        assert "Python" in report
        assert "FastAPI" in report
        assert "## Non-Functional Requirements" in report
        assert "High" in report
        assert "99.9%" in report
        assert "## Architecture Diagram" in report
        assert "graph TD" in report
        assert "## Architectural Considerations" in report
        assert "Security" in report
        assert "Performance" in report


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
