"""
Tests for mcp_server.tools.
Generated by rapid_test_generator.py
"""

import pytest
from unittest.mock import MagicMock, patch

try:
    from mcp_server.tools import (
        get_synthesis_job,
        set_synthesis_job,
        update_synthesis_job,
        get_unified_search,
        get_dependency_analyzer,
        get_assistant,
        register_all_tools,
        register_all_resources,
        register_all_prompts
    )
    IMPORTS_AVAILABLE = True
except ImportError as e:
    print(f"Import error for mcp_server.tools: {e}")
    IMPORTS_AVAILABLE = False



@pytest.mark.skipif(not IMPORTS_AVAILABLE, reason="Module not available")
def test_get_synthesis_job_exists():
    """Should have get_synthesis_job function."""
    assert callable(get_synthesis_job)


@pytest.mark.skipif(not IMPORTS_AVAILABLE, reason="Module not available")
def test_set_synthesis_job_exists():
    """Should have set_synthesis_job function."""
    assert callable(set_synthesis_job)


@pytest.mark.skipif(not IMPORTS_AVAILABLE, reason="Module not available")
def test_update_synthesis_job_exists():
    """Should have update_synthesis_job function."""
    assert callable(update_synthesis_job)


@pytest.mark.skipif(not IMPORTS_AVAILABLE, reason="Module not available")
def test_get_unified_search_exists():
    """Should have get_unified_search function."""
    assert callable(get_unified_search)


@pytest.mark.skipif(not IMPORTS_AVAILABLE, reason="Module not available")
def test_get_dependency_analyzer_exists():
    """Should have get_dependency_analyzer function."""
    assert callable(get_dependency_analyzer)


@pytest.mark.skipif(not IMPORTS_AVAILABLE, reason="Module not available")
def test_get_assistant_exists():
    """Should have get_assistant function."""
    assert callable(get_assistant)


@pytest.mark.skipif(not IMPORTS_AVAILABLE, reason="Module not available")
def test_register_all_tools_exists():
    """Should have register_all_tools function."""
    assert callable(register_all_tools)


@pytest.mark.skipif(not IMPORTS_AVAILABLE, reason="Module not available")
def test_register_all_resources_exists():
    """Should have register_all_resources function."""
    assert callable(register_all_resources)


@pytest.mark.skipif(not IMPORTS_AVAILABLE, reason="Module not available")
def test_register_all_prompts_exists():
    """Should have register_all_prompts function."""
    assert callable(register_all_prompts)



if __name__ == '__main__':
    pytest.main([__file__, '-v'])
