"""
Tests for memory.mem0_integration.
Generated by rapid_test_generator.py
"""

import os
from unittest.mock import MagicMock, patch

import pytest

os.environ["APP_ENV"] = "testing"

try:
    from src.memory.mem0_integration import MemoryCategory

    IMPORTS_AVAILABLE = True
except ImportError as e:
    print(f"Import error for memory.mem0_integration: {e}")
    IMPORTS_AVAILABLE = False


class TestMemoryCategory:
    """Test MemoryCategory."""

    @pytest.mark.skipif(not IMPORTS_AVAILABLE, reason="Module not available")
    def test_memory_category_values(self):
        """Should have correct MemoryCategory values."""
        assert MemoryCategory.PREFERENCE.value == "preference"
        assert MemoryCategory.DECISION.value == "decision"
        assert MemoryCategory.PATTERN.value == "pattern"


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
