"""
Tests for discovery.firecrawl_client.
Generated by rapid_test_generator.py
"""

import os
import pytest
from unittest.mock import MagicMock, patch

os.environ["APP_ENV"] = "testing"

try:
    from src.discovery.firecrawl_client import (
        FirecrawlFormat,
        FirecrawlMode
    )
    IMPORTS_AVAILABLE = True
except ImportError as e:
    print(f"Import error for discovery.firecrawl_client: {e}")
    IMPORTS_AVAILABLE = False


class TestFirecrawlFormat:
    """Test FirecrawlFormat."""

    @pytest.mark.skipif(not IMPORTS_AVAILABLE, reason="Module not available")
    def test_firecrawl_format_values(self):
        """Should have correct FirecrawlFormat values."""
        assert FirecrawlFormat.MARKDOWN.value == "markdown"
        assert FirecrawlFormat.HTML.value == "html"


class TestFirecrawlMode:
    """Test FirecrawlMode."""

    @pytest.mark.skipif(not IMPORTS_AVAILABLE, reason="Module not available")
    def test_firecrawl_mode_values(self):
        """Should have correct FirecrawlMode values."""
        assert FirecrawlMode.SCRAPE.value == "scrape"
        assert FirecrawlMode.CRAWL.value == "crawl"



if __name__ == '__main__':
    pytest.main([__file__, '-v'])
