"""
Tests for discovery.kaggle_client.
Generated by rapid_test_generator.py
"""

import os
from unittest.mock import MagicMock, patch

import pytest

os.environ["APP_ENV"] = "testing"

try:
    from src.discovery.kaggle_client import KaggleClient, KaggleResourceType
    IMPORTS_AVAILABLE = True
except ImportError as e:
    print(f"Import error for discovery.kaggle_client: {e}")
    IMPORTS_AVAILABLE = False


class TestKaggleResourceType:
    """Test KaggleResourceType."""

    @pytest.mark.skipif(not IMPORTS_AVAILABLE, reason="Module not available")
    def test_kaggle_resource_type_values(self):
        """Should have correct KaggleResourceType values."""
        assert KaggleResourceType.DATASET.value == "dataset"
        assert KaggleResourceType.COMPETITION.value == "competition"
        assert KaggleResourceType.NOTEBOOK.value == "notebook"



if __name__ == '__main__':
    pytest.main([__file__, '-v'])
