"""
Tests for discovery.gitlab_client.
Generated by rapid_test_generator.py
"""

import os
from unittest.mock import MagicMock, patch

import pytest

os.environ["APP_ENV"] = "testing"

try:
    from src.discovery.gitlab_client import (
        GitLabClient,
        GitLabSort,
        GitLabState,
        GitLabVisibility,
    )

    IMPORTS_AVAILABLE = True
except ImportError as e:
    print(f"Import error for discovery.gitlab_client: {e}")
    IMPORTS_AVAILABLE = False


class TestGitLabVisibility:
    """Test GitLabVisibility."""

    @pytest.mark.skipif(not IMPORTS_AVAILABLE, reason="Module not available")
    def test_gitlab_visibility_values(self):
        """Should have correct GitLabVisibility values."""
        assert GitLabVisibility.PUBLIC.value == "public"
        assert GitLabVisibility.PRIVATE.value == "private"
        assert GitLabVisibility.INTERNAL.value == "internal"


class TestGitLabState:
    """Test GitLabState."""

    @pytest.mark.skipif(not IMPORTS_AVAILABLE, reason="Module not available")
    def test_gitlab_state_values(self):
        """Should have correct GitLabState values."""
        assert GitLabState.OPENED.value == "opened"
        assert GitLabState.CLOSED.value == "closed"
        assert GitLabState.MERGED.value == "merged"


class TestGitLabSort:
    """Test GitLabSort."""

    @pytest.mark.skipif(not IMPORTS_AVAILABLE, reason="Module not available")
    def test_gitlab_sort_values(self):
        """Should have correct GitLabSort values."""
        assert GitLabSort.CREATED.value == "created_at"
        assert GitLabSort.UPDATED.value == "updated_at"
        assert GitLabSort.NAME.value == "name"


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
