"""
Tests for agents.framework_router.
Generated by rapid_test_generator.py
"""

import os
from unittest.mock import MagicMock, patch

import pytest

os.environ["APP_ENV"] = "testing"

try:
    from src.agents.framework_router import FrameworkType, TaskComplexity, TaskType

    IMPORTS_AVAILABLE = True
except ImportError as e:
    print(f"Import error for agents.framework_router: {e}")
    IMPORTS_AVAILABLE = False


class TestTaskType:
    """Test TaskType."""

    @pytest.mark.skipif(not IMPORTS_AVAILABLE, reason="Module not available")
    def test_task_type_values(self):
        """Should have correct TaskType values."""
        assert TaskType.CODE_REVIEW.value == "code_review"
        assert TaskType.QUICK_FIX.value == "quick_fix"
        assert TaskType.TASK_DECOMPOSITION.value == "task_decomposition"
        assert TaskType.DOCUMENTATION.value == "documentation"
        assert TaskType.SECURITY_AUDIT.value == "security_audit"
        assert TaskType.STATEFUL_WORKFLOW.value == "stateful_workflow"
        assert TaskType.TEAM_COLLABORATION.value == "team_collaboration"
        assert TaskType.DEBUGGING.value == "debugging"
        assert TaskType.FEATURE_DEVELOPMENT.value == "feature_development"


class TestTaskComplexity:
    """Test TaskComplexity."""

    @pytest.mark.skipif(not IMPORTS_AVAILABLE, reason="Module not available")
    def test_task_complexity_values(self):
        """Should have correct TaskComplexity values."""
        assert TaskComplexity.SIMPLE.value == "simple"
        assert TaskComplexity.MEDIUM.value == "medium"
        assert TaskComplexity.COMPLEX.value == "complex"


class TestFrameworkType:
    """Test FrameworkType."""

    @pytest.mark.skipif(not IMPORTS_AVAILABLE, reason="Module not available")
    def test_framework_type_values(self):
        """Should have correct FrameworkType values."""
        assert FrameworkType.AUTOGEN.value == "autogen"
        assert FrameworkType.CREWAI.value == "crewai"
        assert FrameworkType.LANGGRAPH.value == "langgraph"


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
