"""
Test Templates - Jinja2 templates for generating different test types.
"""

UNIT_TEST_TEMPLATE = '''"""
Unit tests for {module_name}
Auto-generated by Enterprise Test Generator
Coverage target: 100%
"""

import pytest
from unittest.mock import Mock, MagicMock, patch, AsyncMock
from typing import Any
{imports}


class Test{class_name}:
    """Unit tests for {full_name}"""
    
    @pytest.fixture
    def mock_dependencies(self):
        """Mock all external dependencies."""
        mocks = {{}}
        {dependency_mocks}
        return mocks
    
{test_methods}
'''

UNIT_TEST_METHOD_SYNC = '''
    def test_{test_name}_happy_path(self{fixture_params}):
        """{docstring}"""
        # Arrange
        {arrange}
        
        # Act
        result = {call}
        
        # Assert
        {assertions}
    
    def test_{test_name}_edge_cases(self{fixture_params}):
        """Test edge cases for {func_name}."""
        {edge_case_tests}
    
    def test_{test_name}_error_handling(self{fixture_params}):
        """Test error handling for {func_name}."""
        {error_tests}
'''

UNIT_TEST_METHOD_ASYNC = '''
    @pytest.mark.asyncio
    async def test_{test_name}_happy_path(self{fixture_params}):
        """{docstring}"""
        # Arrange
        {arrange}
        
        # Act
        result = await {call}
        
        # Assert
        {assertions}
    
    @pytest.mark.asyncio
    async def test_{test_name}_edge_cases(self{fixture_params}):
        """Test edge cases for {func_name}."""
        {edge_case_tests}
    
    @pytest.mark.asyncio
    async def test_{test_name}_error_handling(self{fixture_params}):
        """Test error handling for {func_name}."""
        {error_tests}
'''

INTEGRATION_TEST_TEMPLATE = '''"""
Integration tests for {module_group}
Auto-generated by Enterprise Test Generator
Tests module interactions and data flow.
"""

import pytest
from unittest.mock import Mock, MagicMock, patch, AsyncMock
{imports}


class TestIntegration{group_name}:
    """Integration tests for {module_group} modules."""
    
    @pytest.fixture
    def setup_integration(self):
        """Set up integration test environment."""
        {setup_code}
        yield
        {teardown_code}
    
{test_methods}
'''

INTEGRATION_TEST_METHOD = '''
    @pytest.mark.integration
    def test_{test_name}(self, setup_integration):
        """Integration test: {description}"""
        # Setup
        {setup}
        
        # Execute workflow
        {workflow}
        
        # Verify integration
        {verification}
'''

E2E_TEST_TEMPLATE = '''"""
End-to-End tests for {workflow_name}
Auto-generated by Enterprise Test Generator
Tests complete user workflows.
"""

import pytest
from unittest.mock import Mock, MagicMock, patch, AsyncMock
import asyncio
{imports}


class TestE2E{workflow_class}:
    """End-to-end tests for {workflow_name}."""
    
    @pytest.fixture(scope="class")
    def e2e_setup(self):
        """Set up E2E test environment."""
        {setup_code}
        yield
        {teardown_code}
    
{test_methods}
'''

E2E_TEST_METHOD = '''
    @pytest.mark.e2e
    @pytest.mark.timeout(300)
    def test_e2e_{test_name}(self, e2e_setup):
        """E2E test: {description}"""
        # Step 1: Initialize
        {step1}
        
        # Step 2: Execute main workflow
        {step2}
        
        # Step 3: Verify end state
        {step3}
'''

MOCK_TEMPLATE = '''"""
Centralized mocks for {category}
Auto-generated by Enterprise Test Generator
"""

from unittest.mock import Mock, MagicMock, AsyncMock, patch
from typing import Any, Dict, List, Optional
import pytest


class {mock_class_name}:
    """Mock factory for {category}."""
    
    @staticmethod
    def create_mock({params}) -> MagicMock:
        """Create a configured mock for {category}."""
        mock = MagicMock()
        {mock_config}
        return mock
    
    @staticmethod
    def create_async_mock({params}) -> AsyncMock:
        """Create a configured async mock for {category}."""
        mock = AsyncMock()
        {async_mock_config}
        return mock


{fixtures}
'''

CONFTEST_TEMPLATE = '''"""
Shared test fixtures and configuration.
Auto-generated by Enterprise Test Generator
"""

import pytest
from unittest.mock import Mock, MagicMock, AsyncMock, patch
from typing import Any, Dict, List
import os
import sys

# Add project root to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

{imports}


# ============================================================================
# Environment Fixtures
# ============================================================================

@pytest.fixture(scope="session")
def test_env():
    """Set up test environment variables."""
    env_vars = {env_vars}
    original = {{}}
    for key, value in env_vars.items():
        original[key] = os.environ.get(key)
        os.environ[key] = value
    yield env_vars
    for key, value in original.items():
        if value is None:
            os.environ.pop(key, None)
        else:
            os.environ[key] = value


# ============================================================================
# Mock Fixtures
# ============================================================================

{mock_fixtures}


# ============================================================================
# Helper Functions
# ============================================================================

def assert_called_with_partial(mock, **expected):
    """Assert mock was called with at least the expected kwargs."""
    mock.assert_called()
    actual = mock.call_args.kwargs
    for key, value in expected.items():
        assert key in actual, f"Expected {{key}} in call args"
        assert actual[key] == value, f"Expected {{key}}={{value}}, got {{actual[key]}}"


def create_test_data(data_type: str, **kwargs) -> Any:
    """Create test data for common types."""
    factories = {{
        'repo': lambda: {{'url': 'https://github.com/test/repo', 'name': 'test-repo', **kwargs}},
        'config': lambda: {{'debug': True, 'timeout': 30, **kwargs}},
        'user': lambda: {{'id': 1, 'name': 'test_user', **kwargs}},
    }}
    return factories.get(data_type, lambda: kwargs)()
'''

PYTEST_INI_TEMPLATE = '''[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
asyncio_mode = auto
addopts = -v --tb=short --strict-markers -x
markers =
    unit: Unit tests
    integration: Integration tests
    e2e: End-to-end tests
    slow: Slow tests
    external: Tests requiring external services
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
timeout = 60
'''
