"""
Tests for quality.quality_gate.
Generated by rapid_test_generator.py
"""

import os
import pytest
from unittest.mock import MagicMock, patch

os.environ["APP_ENV"] = "testing"

try:
    from src.quality.quality_gate import (
        GateStatus,
        FixStatus,
        QualityMetrics,
        QualityGate
    )
    IMPORTS_AVAILABLE = True
except ImportError as e:
    print(f"Import error for quality.quality_gate: {e}")
    IMPORTS_AVAILABLE = False


class TestGateStatus:
    """Test GateStatus."""

    @pytest.mark.skipif(not IMPORTS_AVAILABLE, reason="Module not available")
    def test_gate_status_values(self):
        """Should have correct GateStatus values."""
        assert GateStatus.PASSED.value == "passed"
        assert GateStatus.FAILED.value == "failed"
        assert GateStatus.WARNING.value == "warning"


class TestFixStatus:
    """Test FixStatus."""

    @pytest.mark.skipif(not IMPORTS_AVAILABLE, reason="Module not available")
    def test_fix_status_values(self):
        """Should have correct FixStatus values."""
        assert FixStatus.APPLIED.value == "applied"
        assert FixStatus.FAILED.value == "failed"


class TestQualityMetrics:
    """Test QualityMetrics."""

    @pytest.mark.skipif(not IMPORTS_AVAILABLE, reason="Module not available")
    def test_create_qualitymetrics(self):
        """Should create QualityMetrics."""
        instance = QualityMetrics(
            security_score=90.0,
            lint_score=85.0,
            test_coverage=80.0,
            review_score=7.5,
            overall_score=85.0
        )
        assert instance is not None
        assert instance.security_score == 90.0
        assert instance.test_coverage == 80.0



if __name__ == '__main__':
    pytest.main([__file__, '-v'])
