"""
Tests for platform.browser_automation.
Generated by rapid_test_generator.py
"""

import os
import pytest
from unittest.mock import MagicMock, patch

os.environ["APP_ENV"] = "testing"

try:
    from src.platform.browser_automation import (
        BrowserType,
        ViewportSize
    )
    IMPORTS_AVAILABLE = True
except ImportError as e:
    print(f"Import error for platform.browser_automation: {e}")
    IMPORTS_AVAILABLE = False


class TestBrowserType:
    """Test BrowserType."""

    @pytest.mark.skipif(not IMPORTS_AVAILABLE, reason="Module not available")
    def test_browser_type_values(self):
        """Should have correct BrowserType values."""
        assert BrowserType.CHROMIUM.value == "chromium"
        assert BrowserType.FIREFOX.value == "firefox"
        assert BrowserType.WEBKIT.value == "webkit"


class TestViewportSize:
    """Test ViewportSize."""

    @pytest.mark.skipif(not IMPORTS_AVAILABLE, reason="Module not available")
    def test_viewport_size_values(self):
        """Should have correct ViewportSize values."""
        assert ViewportSize.DESKTOP.value == (1920, 1080)
        assert ViewportSize.TABLET.value == (768, 1024)
        assert ViewportSize.MOBILE.value == (375, 667)



if __name__ == '__main__':
    pytest.main([__file__, '-v'])
